services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: exchange_user
      POSTGRES_PASSWORD: exchange_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exchange_user -d exchange"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis-1:
    image: redis:7-alpine
    container_name: redis-1
    network_mode: host
    command:
      redis-server
      --port 7001
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7001", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 10

  redis-2:
    image: redis:7-alpine
    container_name: redis-2
    network_mode: host
    command:
      redis-server
      --port 7002
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7002", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 10

  redis-3:
    image: redis:7-alpine
    container_name: redis-3
    command:
      redis-server
      --port 7003
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
    network_mode: host
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7003", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 10

  redis-4:
    image: redis:7-alpine
    container_name: redis-4
    command:
      redis-server
      --port 7004
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
    network_mode: host
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7004", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 10

  redis-5:
    image: redis:7-alpine
    container_name: redis-5
    command:
      redis-server
      --port 7005
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
    network_mode: host
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7005", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 10

  redis-6:
    image: redis:7-alpine
    container_name: redis-6
    command:
      redis-server
      --port 7006
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
    network_mode: host
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7006", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 10

  kafka1:
    image: apache/kafka:4.0.0
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:19092"
    volumes:
      - kafka1-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false

  kafka2:
    image: apache/kafka:4.0.0
    container_name: kafka2
    hostname: kafka2
    ports:
      - "9093:19093"
    volumes:
      - kafka2-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:19093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false

  kafka3:
    image: apache/kafka:4.0.0
    container_name: kafka3
    hostname: kafka3
    ports:
      - "9094:19094"
    volumes:
      - kafka3-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:19094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false

  redis-cluster-init:
    image: redis:7-alpine
    container_name: redis-cluster-init
    network_mode: host
    depends_on:
      redis-1:
        condition: service_healthy
      redis-2:
        condition: service_healthy
      redis-3:
        condition: service_healthy
      redis-4:
        condition: service_healthy
      redis-5:
        condition: service_healthy
      redis-6:
        condition: service_healthy
    command: >
      redis-cli --cluster create
      127.0.0.1:7001
      127.0.0.1:7002
      127.0.0.1:7003
      127.0.0.1:7004
      127.0.0.1:7005
      127.0.0.1:7006
      --cluster-replicas 1
      --cluster-yes


volumes:
  postgres-data:
  redis1-data:
  redis2-data:
  redis3-data:
  redis4-data:
  redis5-data:
  redis6-data:
  kafka1-data:
  kafka2-data:
  kafka3-data:
