server:
  servlet:
    context-path: /api/v1
spring:
  application:
    name: trading
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange
    username: exchange_user
    password: exchange_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    redisson:
      file: classpath:redisson.yml
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: matching-engine-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.trading.event"
      auto-offset-reset: earliest

jwt:
  secret:
    key: "thispasswordisverytoughtocrackevenicant"