server:
  servlet:
    context-path: /api/v1
spring:
  application:
    name: trading
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange
    username: exchange_user
    password: exchange_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    redisson:
      file: classpath:redisson.yml
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
jwt:
  secret:
    key: "thispasswordisverytoughtocrackevenicant"